---
dist: xenial
language: java
cache:
  directories:
  - $HOME/.m2
  - ~/.ansible/roles
  - ~/.terraform
  pip: true
  apt: true

before_script:
 - sudo apt-get update -q
 - sudo apt-get install -q python-pip 
 - pip install --upgrade --user ansible
 - ansible --version
 - ansible-galaxy install -r ansible/requirements.yml
 # Installs Packer and Terraform used in deployment steps
 - ansible-playbook -i localhost ansible/prepare_deploy_server.yml

jobs:
 include:

  - stage: test
    name: Test App
    before_script: skip # needs change
    script: make test

  - stage: deploy
    name: Build AMI and deploy to ASG
    script: | 
      make bake
      AMIID=$(cat manifest.json | jq -r .builds[0].artifact_id |  cut -d':' -f2)
      make deploy AMIID=$AMIID

